//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DeanIS.Net.Apis.Yellowbook {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    [System.Xml.Serialization.XmlRootAttribute("DetailResults", Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5", IsNullable=true)]
    public partial class BusinessDetailResults25 {
        
        private Error25 errorInformationField;
        
        private SessionInfo25 sessionInfoField;
        
        private Category25[] categoriesField;
        
        private Listing25[] listingsField;
        
        private StatusInfo25 statusField;
        
        /// <remarks/>
        public Error25 ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
        
        /// <remarks/>
        public SessionInfo25 SessionInfo {
            get {
                return this.sessionInfoField;
            }
            set {
                this.sessionInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Category")]
        public Category25[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Listing")]
        public Listing25[] Listings {
            get {
                return this.listingsField;
            }
            set {
                this.listingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusInfo25 Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Error25 {
        
        private string requestUrlField;
        
        private string stackTraceField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string requestUrl {
            get {
                return this.requestUrlField;
            }
            set {
                this.requestUrlField = value;
            }
        }
        
        /// <remarks/>
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Banner25 {
        
        private string destinationUrlField;
        
        private MediaType25 mediaTypeField;
        
        private string mediaUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaType25 MediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MediaUrl {
            get {
                return this.mediaUrlField;
            }
            set {
                this.mediaUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public enum MediaType25 {
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Flash,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class ListingSummaryCollection25 {
        
        private Listing25[] listingField;
        
        private int totalListingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Listing")]
        public Listing25[] Listing {
            get {
                return this.listingField;
            }
            set {
                this.listingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TotalListings {
            get {
                return this.totalListingsField;
            }
            set {
                this.totalListingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Listing25 {
        
        private string[] aboutUsField;
        
        private Address25[] locationsField;
        
        private string[] brandsField;
        
        private ContactInfo25 contactInfoField;
        
        private CreditCards25 creditCardsField;
        
        private Hours25 hoursField;
        
        private Media25 mediaField;
        
        private ReviewCollection25 reviewsField;
        
        private bool hasTheaterVerticalDataField;
        
        private TheaterInfo25 theaterInfoField;
        
        private bool businessVerifiedField;
        
        private int yearsInBusinessField;
        
        private string chainNameField;
        
        private string[] languagesField;
        
        private string[] productsField;
        
        private string[] servicesField;
        
        private string[] specialServicesField;
        
        private string[] otherField;
        
        private string[] chainsField;
        
        private string[] generalField;
        
        private string[] certificationsField;
        
        private string[] associationsField;
        
        private int videoscapeIdField;
        
        private CouponInfo25 couponInfoField;
        
        private OpenTable25 openTableField;
        
        private string categoriesField;
        
        private string distanceField;
        
        private long listingIdField;
        
        private string listingTypeField;
        
        private string nameField;
        
        private float relevancyField;
        
        private string tagLineField;
        
        private string virtualDomainUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] AboutUs {
            get {
                return this.aboutUsField;
            }
            set {
                this.aboutUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Location")]
        public Address25[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Brands {
            get {
                return this.brandsField;
            }
            set {
                this.brandsField = value;
            }
        }
        
        /// <remarks/>
        public ContactInfo25 ContactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        public CreditCards25 CreditCards {
            get {
                return this.creditCardsField;
            }
            set {
                this.creditCardsField = value;
            }
        }
        
        /// <remarks/>
        public Hours25 Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        public Media25 Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        public ReviewCollection25 Reviews {
            get {
                return this.reviewsField;
            }
            set {
                this.reviewsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTheaterVerticalData {
            get {
                return this.hasTheaterVerticalDataField;
            }
            set {
                this.hasTheaterVerticalDataField = value;
            }
        }
        
        /// <remarks/>
        public TheaterInfo25 TheaterInfo {
            get {
                return this.theaterInfoField;
            }
            set {
                this.theaterInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool BusinessVerified {
            get {
                return this.businessVerifiedField;
            }
            set {
                this.businessVerifiedField = value;
            }
        }
        
        /// <remarks/>
        public int YearsInBusiness {
            get {
                return this.yearsInBusinessField;
            }
            set {
                this.yearsInBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string ChainName {
            get {
                return this.chainNameField;
            }
            set {
                this.chainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] SpecialServices {
            get {
                return this.specialServicesField;
            }
            set {
                this.specialServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Chains {
            get {
                return this.chainsField;
            }
            set {
                this.chainsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] General {
            get {
                return this.generalField;
            }
            set {
                this.generalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Certifications {
            get {
                return this.certificationsField;
            }
            set {
                this.certificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bullet")]
        public string[] Associations {
            get {
                return this.associationsField;
            }
            set {
                this.associationsField = value;
            }
        }
        
        /// <remarks/>
        public int VideoscapeId {
            get {
                return this.videoscapeIdField;
            }
            set {
                this.videoscapeIdField = value;
            }
        }
        
        /// <remarks/>
        public CouponInfo25 CouponInfo {
            get {
                return this.couponInfoField;
            }
            set {
                this.couponInfoField = value;
            }
        }
        
        /// <remarks/>
        public OpenTable25 OpenTable {
            get {
                return this.openTableField;
            }
            set {
                this.openTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ListingId {
            get {
                return this.listingIdField;
            }
            set {
                this.listingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ListingType {
            get {
                return this.listingTypeField;
            }
            set {
                this.listingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Relevancy {
            get {
                return this.relevancyField;
            }
            set {
                this.relevancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TagLine {
            get {
                return this.tagLineField;
            }
            set {
                this.tagLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VirtualDomainUrl {
            get {
                return this.virtualDomainUrlField;
            }
            set {
                this.virtualDomainUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Address25 {
        
        private string address1Field;
        
        private string address2Field;
        
        private int addressIdField;
        
        private string cityField;
        
        private string freeTextField;
        
        private long natsMatchListingIdField;
        
        private string phoneField;
        
        private string stateField;
        
        private string zipField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FreeText {
            get {
                return this.freeTextField;
            }
            set {
                this.freeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NatsMatchListingId {
            get {
                return this.natsMatchListingIdField;
            }
            set {
                this.natsMatchListingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class ContactInfo25 {
        
        private Website25[] websitesField;
        
        private string secondaryNumberField;
        
        private string mobileNumberField;
        
        private string officeNumberField;
        
        private string homeNumberField;
        
        private string afterHoursNumberField;
        
        private string dataNumberField;
        
        private string[] emailAddressesField;
        
        private string faxNumberField;
        
        private string tollFreeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Website")]
        public Website25[] Websites {
            get {
                return this.websitesField;
            }
            set {
                this.websitesField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryNumber {
            get {
                return this.secondaryNumberField;
            }
            set {
                this.secondaryNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeNumber {
            get {
                return this.officeNumberField;
            }
            set {
                this.officeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HomeNumber {
            get {
                return this.homeNumberField;
            }
            set {
                this.homeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AfterHoursNumber {
            get {
                return this.afterHoursNumberField;
            }
            set {
                this.afterHoursNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DataNumber {
            get {
                return this.dataNumberField;
            }
            set {
                this.dataNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] EmailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TollFreeNumber {
            get {
                return this.tollFreeNumberField;
            }
            set {
                this.tollFreeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Website25 {
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class CreditCards25 {
        
        private bool americanExpressField;
        
        private bool carteBlancheField;
        
        private bool customField;
        
        private bool dinersField;
        
        private bool discoverField;
        
        private bool masterCardField;
        
        private bool visaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AmericanExpress {
            get {
                return this.americanExpressField;
            }
            set {
                this.americanExpressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CarteBlanche {
            get {
                return this.carteBlancheField;
            }
            set {
                this.carteBlancheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Custom {
            get {
                return this.customField;
            }
            set {
                this.customField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Diners {
            get {
                return this.dinersField;
            }
            set {
                this.dinersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Discover {
            get {
                return this.discoverField;
            }
            set {
                this.discoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MasterCard {
            get {
                return this.masterCardField;
            }
            set {
                this.masterCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Visa {
            get {
                return this.visaField;
            }
            set {
                this.visaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Hours25 {
        
        private string fridayField;
        
        private string mondayField;
        
        private string saturdayField;
        
        private string sundayField;
        
        private string textField;
        
        private string thursdayField;
        
        private string tuesdayField;
        
        private string wednesdayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Friday {
            get {
                return this.fridayField;
            }
            set {
                this.fridayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Monday {
            get {
                return this.mondayField;
            }
            set {
                this.mondayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Saturday {
            get {
                return this.saturdayField;
            }
            set {
                this.saturdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sunday {
            get {
                return this.sundayField;
            }
            set {
                this.sundayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Thursday {
            get {
                return this.thursdayField;
            }
            set {
                this.thursdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tuesday {
            get {
                return this.tuesdayField;
            }
            set {
                this.tuesdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Wednesday {
            get {
                return this.wednesdayField;
            }
            set {
                this.wednesdayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Media25 {
        
        private VideoAd25 videoAdField;
        
        private string bookScanUrlField;
        
        private string logoUrlField;
        
        private string menuUrlField;
        
        private string videoscapeUrlField;
        
        /// <remarks/>
        public VideoAd25 VideoAd {
            get {
                return this.videoAdField;
            }
            set {
                this.videoAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookScanUrl {
            get {
                return this.bookScanUrlField;
            }
            set {
                this.bookScanUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuUrl {
            get {
                return this.menuUrlField;
            }
            set {
                this.menuUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VideoscapeUrl {
            get {
                return this.videoscapeUrlField;
            }
            set {
                this.videoscapeUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class VideoAd25 {
        
        private string mp4UrlField;
        
        private string swfUrlField;
        
        private string thumbField;
        
        private string wmvUrlField;
        
        private string videoAdCaptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mp4Url {
            get {
                return this.mp4UrlField;
            }
            set {
                this.mp4UrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SwfUrl {
            get {
                return this.swfUrlField;
            }
            set {
                this.swfUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WmvUrl {
            get {
                return this.wmvUrlField;
            }
            set {
                this.wmvUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VideoAdCaption {
            get {
                return this.videoAdCaptionField;
            }
            set {
                this.videoAdCaptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class ReviewCollection25 {
        
        private Review25[] reviewField;
        
        private float averageReviewScoreField;
        
        private int totalNumberOfRatingsField;
        
        private int totalNumberOfReviewsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Review")]
        public Review25[] Review {
            get {
                return this.reviewField;
            }
            set {
                this.reviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AverageReviewScore {
            get {
                return this.averageReviewScoreField;
            }
            set {
                this.averageReviewScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TotalNumberOfRatings {
            get {
                return this.totalNumberOfRatingsField;
            }
            set {
                this.totalNumberOfRatingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TotalNumberOfReviews {
            get {
                return this.totalNumberOfReviewsField;
            }
            set {
                this.totalNumberOfReviewsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Review25 : AbstractReviewItem25 {
        
        private Comment25[] commentsField;
        
        private UserInfo25 userInfoField;
        
        private int ratingField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Comment")]
        public Comment25[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public UserInfo25 UserInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Comment25 : AbstractReviewItem25 {
        
        private UserInfo25 userInfoField;
        
        /// <remarks/>
        public UserInfo25 UserInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class UserInfo25 {
        
        private string userNameField;
        
        private string displayNameField;
        
        private string eIDField;
        
        private UserInfoAuthenticationTypeEnumMaster authenticationTypeField;
        
        private string facebookIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EID {
            get {
                return this.eIDField;
            }
            set {
                this.eIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UserInfoAuthenticationTypeEnumMaster AuthenticationType {
            get {
                return this.authenticationTypeField;
            }
            set {
                this.authenticationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FacebookId {
            get {
                return this.facebookIdField;
            }
            set {
                this.facebookIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public enum UserInfoAuthenticationTypeEnumMaster {
        
        /// <remarks/>
        FacebookConnect,
        
        /// <remarks/>
        MyYellowbook,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Comment25))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Review25))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class AbstractReviewItem25 {
        
        private System.DateTime dateCreatedField;
        
        private string reviewItemIdField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReviewItemId {
            get {
                return this.reviewItemIdField;
            }
            set {
                this.reviewItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class TheaterInfo25 {
        
        private TheaterAmenitiesEnum25[] amenitiesField;
        
        private MovieInfo25[] moviesField;
        
        private string[] showDatesField;
        
        private string theaterNameField;
        
        private int screensField;
        
        private string seatingField;
        
        private string soundSystemField;
        
        private string pricingAdultField;
        
        private string pricingChildField;
        
        private string pricingSeniorField;
        
        private string pricingAdultBargainField;
        
        private string pricingCommentField;
        
        private bool ticketingViaMovieTicketsDotComField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Amenity", IsNullable=false)]
        public TheaterAmenitiesEnum25[] Amenities {
            get {
                return this.amenitiesField;
            }
            set {
                this.amenitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Movie")]
        public MovieInfo25[] Movies {
            get {
                return this.moviesField;
            }
            set {
                this.moviesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ShowDate")]
        public string[] ShowDates {
            get {
                return this.showDatesField;
            }
            set {
                this.showDatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TheaterName {
            get {
                return this.theaterNameField;
            }
            set {
                this.theaterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Screens {
            get {
                return this.screensField;
            }
            set {
                this.screensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Seating {
            get {
                return this.seatingField;
            }
            set {
                this.seatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SoundSystem {
            get {
                return this.soundSystemField;
            }
            set {
                this.soundSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingAdult {
            get {
                return this.pricingAdultField;
            }
            set {
                this.pricingAdultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingChild {
            get {
                return this.pricingChildField;
            }
            set {
                this.pricingChildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingSenior {
            get {
                return this.pricingSeniorField;
            }
            set {
                this.pricingSeniorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingAdultBargain {
            get {
                return this.pricingAdultBargainField;
            }
            set {
                this.pricingAdultBargainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PricingComment {
            get {
                return this.pricingCommentField;
            }
            set {
                this.pricingCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool TicketingViaMovieTicketsDotCom {
            get {
                return this.ticketingViaMovieTicketsDotComField;
            }
            set {
                this.ticketingViaMovieTicketsDotComField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public enum TheaterAmenitiesEnum25 {
        
        /// <remarks/>
        WheelchairAccessible,
        
        /// <remarks/>
        THXCertifiedTheater,
        
        /// <remarks/>
        CafeOnPremises,
        
        /// <remarks/>
        PrintAtHomeTicketing,
        
        /// <remarks/>
        KioskForTicketPickup,
        
        /// <remarks/>
        StadiumSeating,
        
        /// <remarks/>
        GameRoomOnPremises,
        
        /// <remarks/>
        ListeningDevicesAvailable,
        
        /// <remarks/>
        PreferredParkingAvailable,
        
        /// <remarks/>
        PartyRoomAvailable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class MovieInfo25 {
        
        private string[] photosField;
        
        private string[] hiResPhotosField;
        
        private string[] genresField;
        
        private string[] castField;
        
        private MovieReleaseDate25[] releaseDatesField;
        
        private string[] producersField;
        
        private string[] writersField;
        
        private string[] synopsisField;
        
        private string[] criticalReviewField;
        
        private MovieShowDate25[] showDatesField;
        
        private string buyTicketsUrlField;
        
        private string nameField;
        
        private string movieIdField;
        
        private string mPAARatingField;
        
        private string mPAAAdvisoryField;
        
        private string directorField;
        
        private int runningTimeField;
        
        private string webSiteField;
        
        private string distributorField;
        
        private float starsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Photo")]
        public string[] Photos {
            get {
                return this.photosField;
            }
            set {
                this.photosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HiResPhoto")]
        public string[] HiResPhotos {
            get {
                return this.hiResPhotosField;
            }
            set {
                this.hiResPhotosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Genre")]
        public string[] Genres {
            get {
                return this.genresField;
            }
            set {
                this.genresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Member")]
        public string[] Cast {
            get {
                return this.castField;
            }
            set {
                this.castField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ReleaseDate")]
        public MovieReleaseDate25[] ReleaseDates {
            get {
                return this.releaseDatesField;
            }
            set {
                this.releaseDatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Producer")]
        public string[] Producers {
            get {
                return this.producersField;
            }
            set {
                this.producersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Writer")]
        public string[] Writers {
            get {
                return this.writersField;
            }
            set {
                this.writersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Paragraph")]
        public string[] Synopsis {
            get {
                return this.synopsisField;
            }
            set {
                this.synopsisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Paragraph")]
        public string[] CriticalReview {
            get {
                return this.criticalReviewField;
            }
            set {
                this.criticalReviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ShowDate")]
        public MovieShowDate25[] ShowDates {
            get {
                return this.showDatesField;
            }
            set {
                this.showDatesField = value;
            }
        }
        
        /// <remarks/>
        public string BuyTicketsUrl {
            get {
                return this.buyTicketsUrlField;
            }
            set {
                this.buyTicketsUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MovieId {
            get {
                return this.movieIdField;
            }
            set {
                this.movieIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MPAARating {
            get {
                return this.mPAARatingField;
            }
            set {
                this.mPAARatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MPAAAdvisory {
            get {
                return this.mPAAAdvisoryField;
            }
            set {
                this.mPAAAdvisoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RunningTime {
            get {
                return this.runningTimeField;
            }
            set {
                this.runningTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WebSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Distributor {
            get {
                return this.distributorField;
            }
            set {
                this.distributorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class MovieReleaseDate25 {
        
        private string notesField;
        
        private string displayDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayDate {
            get {
                return this.displayDateField;
            }
            set {
                this.displayDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class MovieShowDate25 {
        
        private MovieShowTime25[] showTimesField;
        
        private string dateField;
        
        private string showAttributesField;
        
        private bool showPassesField;
        
        private bool showFestivalField;
        
        private string soundField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ShowTime")]
        public MovieShowTime25[] ShowTimes {
            get {
                return this.showTimesField;
            }
            set {
                this.showTimesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowAttributes {
            get {
                return this.showAttributesField;
            }
            set {
                this.showAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ShowPasses {
            get {
                return this.showPassesField;
            }
            set {
                this.showPassesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ShowFestival {
            get {
                return this.showFestivalField;
            }
            set {
                this.showFestivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sound {
            get {
                return this.soundField;
            }
            set {
                this.soundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class MovieShowTime25 {
        
        private bool discountedTicketPriceField;
        
        private string timeField;
        
        private string buyTicketsUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DiscountedTicketPrice {
            get {
                return this.discountedTicketPriceField;
            }
            set {
                this.discountedTicketPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BuyTicketsUrl {
            get {
                return this.buyTicketsUrlField;
            }
            set {
                this.buyTicketsUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class CouponInfo25 {
        
        private Coupon25[] couponsField;
        
        private bool hasCouponField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Coupon")]
        public Coupon25[] Coupons {
            get {
                return this.couponsField;
            }
            set {
                this.couponsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasCoupon {
            get {
                return this.hasCouponField;
            }
            set {
                this.hasCouponField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Coupon25 {
        
        private bool hasCouponField;
        
        private string defaultRenderingHtmlField;
        
        private string expirationField;
        
        private string offerField;
        
        private string[] restrictionsField;
        
        private string providerField;
        
        private string urlField;
        
        private string thumbnailField;
        
        /// <remarks/>
        public bool HasCoupon {
            get {
                return this.hasCouponField;
            }
            set {
                this.hasCouponField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultRenderingHtml {
            get {
                return this.defaultRenderingHtmlField;
            }
            set {
                this.defaultRenderingHtmlField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        public string Offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Restrictions")]
        public string[] Restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class OpenTable25 {
        
        private string restaurantIDField;
        
        private string reservationUrlField;
        
        private string mobileReservationUrlField;
        
        /// <remarks/>
        public string RestaurantID {
            get {
                return this.restaurantIDField;
            }
            set {
                this.restaurantIDField = value;
            }
        }
        
        /// <remarks/>
        public string ReservationUrl {
            get {
                return this.reservationUrlField;
            }
            set {
                this.reservationUrlField = value;
            }
        }
        
        /// <remarks/>
        public string MobileReservationUrl {
            get {
                return this.mobileReservationUrlField;
            }
            set {
                this.mobileReservationUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class SearchInfo25 {
        
        private SessionInfo25 sessionInfoField;
        
        private Category25[] categoriesField;
        
        private string expandedLocationField;
        
        private bool geoExpandedField;
        
        private string originalLocationField;
        
        /// <remarks/>
        public SessionInfo25 SessionInfo {
            get {
                return this.sessionInfoField;
            }
            set {
                this.sessionInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Category")]
        public Category25[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExpandedLocation {
            get {
                return this.expandedLocationField;
            }
            set {
                this.expandedLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool GeoExpanded {
            get {
                return this.geoExpandedField;
            }
            set {
                this.geoExpandedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginalLocation {
            get {
                return this.originalLocationField;
            }
            set {
                this.originalLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class SessionInfo25 {
        
        private string searchIdField;
        
        private string sessionIdField;
        
        private string visitorIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string searchId {
            get {
                return this.searchIdField;
            }
            set {
                this.searchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visitorId {
            get {
                return this.visitorIdField;
            }
            set {
                this.visitorIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Category25 {
        
        private int idField;
        
        private string nameField;
        
        private float listingCountField;
        
        private float relevancyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ListingCount {
            get {
                return this.listingCountField;
            }
            set {
                this.listingCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Relevancy {
            get {
                return this.relevancyField;
            }
            set {
                this.relevancyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class AlphaFilter25 {
        
        private string parameterNameField;
        
        private string parameterValueField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class FilterItem25 {
        
        private int countField;
        
        private string parameterValueField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class FilterGroup25 {
        
        private FilterItem25[] filterItemsField;
        
        private string parameterNameField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FilterItem")]
        public FilterItem25[] FilterItems {
            get {
                return this.filterItemsField;
            }
            set {
                this.filterItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public partial class Refinements25 {
        
        private string[] popularTermsField;
        
        private string[] expandLocationsField;
        
        private FilterGroup25[] filtersField;
        
        private string[] narrowLocationsField;
        
        private AlphaFilter25 alphaFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Term")]
        public string[] PopularTerms {
            get {
                return this.popularTermsField;
            }
            set {
                this.popularTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Where")]
        public string[] ExpandLocations {
            get {
                return this.expandLocationsField;
            }
            set {
                this.expandLocationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Filter")]
        public FilterGroup25[] Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Where")]
        public string[] NarrowLocations {
            get {
                return this.narrowLocationsField;
            }
            set {
                this.narrowLocationsField = value;
            }
        }
        
        /// <remarks/>
        public AlphaFilter25 AlphaFilter {
            get {
                return this.alphaFilterField;
            }
            set {
                this.alphaFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    public enum StatusInfo25 {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        NoResultsFound,
        
        /// <remarks/>
        UnhandledException,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5")]
    [System.Xml.Serialization.XmlRootAttribute("SearchResults", Namespace="http://yellowbook.com/YellowBookSearchResponseSchema/v2/5", IsNullable=true)]
    public partial class BusinessSearchResults25 {
        
        private Error25 errorInformationField;
        
        private Refinements25 refinementsField;
        
        private SearchInfo25 searchInfoField;
        
        private ListingSummaryCollection25 alsoServingListingsField;
        
        private Banner25 bannerField;
        
        private ListingSummaryCollection25 inAreaListingsField;
        
        private StatusInfo25 statusField;
        
        /// <remarks/>
        public Error25 ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
            }
        }
        
        /// <remarks/>
        public Refinements25 Refinements {
            get {
                return this.refinementsField;
            }
            set {
                this.refinementsField = value;
            }
        }
        
        /// <remarks/>
        public SearchInfo25 SearchInfo {
            get {
                return this.searchInfoField;
            }
            set {
                this.searchInfoField = value;
            }
        }
        
        /// <remarks/>
        public ListingSummaryCollection25 AlsoServingListings {
            get {
                return this.alsoServingListingsField;
            }
            set {
                this.alsoServingListingsField = value;
            }
        }
        
        /// <remarks/>
        public Banner25 Banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        /// <remarks/>
        public ListingSummaryCollection25 InAreaListings {
            get {
                return this.inAreaListingsField;
            }
            set {
                this.inAreaListingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusInfo25 Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
}
